import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + " m-4"}>
        <ul className="list-disc list-inside mb-4">
          {[1, 2, 3, 4].map((n) => (
            <li key={n}>
              <Link href={`/unstable_cache/${n}`} className="text-blue-600">
                /unstable_cache/{n}
              </Link>
            </li>
          ))}
          {[1, 2, 3, 4].map((n) => (
            <li key={n}>
              <Link href={`/fetch/${n}`} className="text-blue-600">
                /fetch/{n}
              </Link>
            </li>
          ))}
          <li>
            <a href="/api/revalidate?tag=test" className="text-blue-600">
              /api/revalidate?tag=test
            </a>
          </li>
        </ul>

        {children}
      </body>
    </html>
  );
}
