import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + " m-4"}>
        <ul className="list-disc list-inside mb-4">
          <li>
            <Link href="/">
              <span className="text-blue-600">/</span> using unstable_cache
            </Link>
          </li>
          <li>
            <Link href="/fetch">
              <span className="text-blue-600">/fetch</span> using fetch with
              tags
            </Link>
          </li>
          <li>
            <a href="/api/revalidate?tag=test" className="text-blue-600">
              /api/revalidate?tag=test
            </a>
          </li>
        </ul>

        {children}
      </body>
    </html>
  );
}
